### ISSUE TITLE
Make jme talk to javafx

### ISSUE THREAD

**Issue by Starkmann** [meltzow/supernovae#12]
For example the HUD must know which unit(s) are selected, to show an image/label

**Comment by meltzow** [comment]
I saw you commit https://github.com/meltzow/supernovae/commit/acdec651488333a2607e5c575d71baf67b72a6c3 ,thats the right way. 
I think I understand you problem, but I dont have any idea to solve it in the moment. I must think about it.

**Comment by meltzow** [comment]
perhaps a solution?? please check this: javaFX has the observable pattern. https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8&client=ubuntu#q=javafx%20observable
 If JME (the hudproc) modify these obserables, javafx should be informed about it.

**Comment by meltzow** [comment]
fixed with https://github.com/meltzow/supernovae/commit/e544a76f7966bb229c987b4f57f82f7ffe626abf
but we should refactor it later.
