### ISSUE TITLE
attacking a enemy

### ISSUE THREAD

**Issue by meltzow** [meltzow/supernovae#13]
- [x] selecting a unit
- [x] right click a enemy
- [x] move in range of the enemy
- [x] fire weapons
- [x] destroy the enemy

**Comment by meltzow** [comment]
brainstorm: 

- component weapon 
- MODE  "melee", "range"

**Comment by Starkmann** [comment]
The AndFilter is not working correctly:
```

FieldFilter<Parenting> childrenOfBB = new FieldFilter<Parenting>(Parenting.class, "parent",commanded.getId());
FieldFilter<Ability> abilities = new FieldFilter<Ability>(Ability.class, "active", false);
FieldFilter<Naming> gunAblities = new FieldFilter<Naming>(Naming.class, "name", "gun");
AndFilter<EntityComponent> allTogether = AndFilter.create(EntityComponent.class, childrenOfBB, abilities, gunAblities);
			
Set<EntityId> entities = enData.findEntities(allTogether);
```

results in empty set

**Comment by meltzow** [comment]
it looks like, the problem is, we filter not a special component, we are filtering more the one components. We must find a solution to find some entities (in the componentdata) which have some things. Currently I cant see a solution in zay-es for that. Perhaps we must extend the component-data.
perhaps see http://jmonkeyengine-contributions.github.io/zay-es/javadoc/zay-es/com/simsilica/es/base/DefaultEntityData.html#getEntityIds(java.lang.Class, com.simsilica.es.ComponentFilter)

**Comment by meltzow** [comment]
perhaps this can help: https://hub.jmonkeyengine.org/t/accessing-childof-entity/30684

**Comment by meltzow** [comment]
here my question at our current problem https://hub.jmonkeyengine.org/t/searching-entities-with-multiple-components/35690

**Comment by meltzow** [comment]
perhaps we are thinking "too big". a solution can be to cut the problem in smaller steps und solve it in separate processors. This is also a solution for https://github.com/meltzow/supernovae/issues/14 
perhaps this scribbel help to understand
![img_20160421_103839](https://cloud.githubusercontent.com/assets/1238001/14703443/2269866c-07b0-11e6-8d02-105fefe47bd6.jpg)

**Comment by meltzow** [comment]
fixed with .... wait for it .... https://github.com/meltzow/supernovae/commit/28dcfd07af861b356f1362553e4a606c9268d1cc
