### ISSUE TITLE
Architecture: GameInputListener is getting too big

### ISSUE THREAD

**Issue by Starkmann** [meltzow/supernovae#14]
We have to take care, the GameInputListener is having to much logic. I think we should move some logic to other classes/processor.

**Comment by meltzow** [comment]
done with: 62b8971a8f543ef4e87041fa0a81344060a0abbf
now the gameinputlistener only emitts a "InputComponnent" with the mousebutton and the target. A InputProc reacts an it. Here we can create commands from the input, like move or attack.

**Comment by Starkmann** [comment]
Nice, thats how it should be done! +1
