### ISSUE TITLE
JavaFX: create sub windows

### ISSUE THREAD

**Issue by Starkmann** [meltzow/supernovae#16]
When you click on "Options" i would like to have a new sub window (e.g. for setting the resolution) like sc2 does it.
![989k0](https://cloud.githubusercontent.com/assets/3470953/14569492/67634642-033f-11e6-9777-4cdfffc7b038.jpg)

**Comment by meltzow** [comment]
http://www.javafxtutorials.com/tutorials/creating-a-pop-up-window-in-javafx/

**Comment by meltzow** [comment]
fixed with https://github.com/meltzow/supernovae/commit/9647bccad1fa65ddef913ee339e1f2ba247486a8
no please integrate FXML and the options
