### ISSUE TITLE
loading texture/material and animations from blend files 

### ISSUE THREAD

**Issue by meltzow** [meltzow/supernovae#19]
how do it?

**Comment by meltzow** [comment]
![unityeditoroverview1](https://cloud.githubusercontent.com/assets/1238001/14817524/202501f4-0bb8-11e6-80ca-5af17478be0b.png)
here it is!! but now we are loading j3o file. `"path":"zeratul/zeratul.j3o",```

**Comment by Starkmann** [comment]
For me the textures are still missing

**Comment by meltzow** [comment]
Jepp, its broken currently

**Comment by meltzow** [comment]
animations are now possible.

**Comment by meltzow** [comment]
ok, working now. We have a nexus (building) with textures and animation.
