### ISSUE TITLE
Master Broken

### ISSUE THREAD

**Issue by Starkmann** [meltzow/supernovae#35]
I can neither start the editor nor the game:

Uncaught exception thrown in Thread[jME3 Main,5,main]
RendererException: compile error in: ShaderSource[name=matdefs/MyTerrainLighting.frag, defines, type=Fragment, language=GLSL100]
0(238) : error C1008: undefined variable "m_DiffuseMap_3_scale"
0(244) : error C1008: undefined variable "m_DiffuseMap_4_scale"
0(249) : error C1008: undefined variable "m_DiffuseMap_5_scale"
0(254) : error C1008: undefined variable "m_DiffuseMap_6_scale"
0(259) : error C1008: undefined variable "m_DiffuseMap_7_scale"

**Comment by meltzow** [comment]
Pull the frag file from buildingqndmining branch

**Comment by Starkmann** [comment]
I'm up to date on that branch. Maybe the file was not commited?

**Comment by meltzow** [comment]
Is there a change? See last commits.remember you must refresh your projects (F5) before its working.try to start Form commandline

**Comment by Starkmann** [comment]
Yes 3  commits:
commit 0cfb3de8d0cda236e36aa8b81cecd93f7010f3e4
    fix mech working
commit 1a396696ac4948ff0db10bb0f09dec14a507df3b
    Mech kann schießen und laufen
commit e2f3f89a502b33dea54df5e5fd2e0132bcbe317b
These files i have:
./game/bin/matdefs/MyTerrainLighting.frag
./core/build/resources/main/matdefs/MyTerrainLighting.frag
./editor/bin/matdefs/MyTerrainLighting.frag
./assets/matdefs/MyTerrainLighting.frag
