### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Starkmann** [meltzow/supernovae#36]
I have a huge  performance drop after merging buildingandMining into ui-design. The buildingandMining as itself also is very slow, only 14fps.

**Comment by meltzow** [comment]
Everything OK at my side.is there anything other running.perhaps you start it twice??

**Comment by meltzow** [comment]
If not please try do find the bottleneck.perhaps you must use a java profiler

**Comment by meltzow** [comment]
any news?

**Comment by meltzow** [comment]
yes same here.

**Comment by Starkmann** [comment]
With closing #37 i do not have any performance issues. Do you?

**Comment by meltzow** [comment]
nope
