### ISSUE TITLE
create simpleGame with JAVAFX 

### ISSUE THREAD

**Issue by meltzow** [meltzow/supernovae#4]
- [ ] inital  menu
- [ ] HUD

for example see here:
https://github.com/empirephoenix/JME3-JFX/blob/master/src/test/java/com/jme3x/jfx/injfx/TestDisplayInImageView.java

**Comment by meltzow** [comment]
now there is a working example.just run  "./gradlew game:run "

**Comment by meltzow** [comment]
Sorry, forget it. its a JavaFX application. I was a little bit confused

**Comment by Starkmann** [comment]
Yeah i checked on that code but it is a bit complicated. Right now i was working on JavaFX only (http://code.makery.ch/library/javafx-8-tutorial/part1/), but i have problems to marriage the scene graph of jmonkey with the one of JavaFX.

**Comment by Starkmann** [comment]
As far a i understand (https://github.com/empirephoenix/JME3-JFX/) wants to offer a bridge between jme and JavaFX

**Comment by meltzow** [comment]
Done now
